apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: microservices
  labels:
    app: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: azneo/microservice1:latest
          ports:
            - containerPort: 8080  # Optional: if serving HTTP
          env:
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "test-topic"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
