apiVersion: v1
kind: Service
metadata:
  name: microservice1
  namespace: microservices  # Add this line to specify the namespace
spec:
  selector:
    app: microservice1  # Must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Use ClusterIP for internal access within the cluster
