apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  namespace: microservices
  labels:
    app: microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: azizishankhojaev/microservice2:latest
          ports:
            - containerPort: 8080  # Optional: if you expose a port
          env:
            - name: KAFKA_BROKER
              value: "kafka.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "test-topic"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
