apiVersion: v1
kind: Service
metadata:
  name: microservice2
  namespace: microservices  # Ensure this is the correct namespace
spec:
  selector:
    app: microservice2  # Match this with the label in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Use ClusterIP for internal access within the cluster
